FROM golang:1.23.1 AS build

WORKDIR /grpc_distr_calc

COPY go.mod go.sum ./

COPY ./cmd/agent/ ./cmd/agent/
COPY ./internal/grpc/agent/ ./internal/grpc/agent/
COPY ./internal/utils/agent/ ./internal/utils/agent/
COPY ./proto ./proto/

ENV AGENT_PORT=5000
ENV AGENT_HOST=0.0.0.0

RUN go mod tidy

RUN go build -o agent cmd/agent/*.go

EXPOSE 5000/tcp

CMD [ "./agent" ]
